spring:
  application:
    name: customer-profile
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway.enabled: true
springdoc.api-docs.path: /api-docs
management.metrics.export.wavefront:
  uri: https://wavefront.surf
  api-token: 962d95ed-bede-4dc5-8761-ec3ef1ad702e
