spring:
  application:
    name: customer-profile
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: sa
    password: password
    driverClassName: org.h2.Driver
springdoc.api-docs.path: /api-docs
spring.flyway.enabled: true
