apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer profile
  description: The Customer Profile API
spec:
  type: openapi
  lifecycle: production
  owner: default-team
  system: tapathon
  definition:
    $text: https://github.com/d-lorenc/tapathon-service/blob/main/catalog/openapi.json
