apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: customer-profile
  namespace: dariusz
  labels:
    apps.tanzu.vmware.com/workload-type: web
#    apps.tanzu.vmware.com/has-tests: true
#    apps.tanzu.vmware.com/supply-chain: scanning
    app.kubernetes.io/part-of: customer-profile
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/d-lorenc/tapathon-service.git
